// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFileFromPathToVault(arg1, arg2) {
  return window['go']['backend']['App']['AddFileFromPathToVault'](arg1, arg2);
}

export function AddFileToVault(arg1) {
  return window['go']['backend']['App']['AddFileToVault'](arg1);
}

export function CreateVaultFolder(arg1) {
  return window['go']['backend']['App']['CreateVaultFolder'](arg1);
}

export function DecryptServerURL() {
  return window['go']['backend']['App']['DecryptServerURL']();
}

export function DecryptURLForVaultPath(arg1) {
  return window['go']['backend']['App']['DecryptURLForVaultPath'](arg1);
}

export function DeleteVaultPath(arg1) {
  return window['go']['backend']['App']['DeleteVaultPath'](arg1);
}

export function FinalizeNewVault(arg1, arg2) {
  return window['go']['backend']['App']['FinalizeNewVault'](arg1, arg2);
}

export function ListVaultFiles() {
  return window['go']['backend']['App']['ListVaultFiles']();
}

export function LockVault() {
  return window['go']['backend']['App']['LockVault']();
}

export function MoveVaultEntry(arg1, arg2) {
  return window['go']['backend']['App']['MoveVaultEntry'](arg1, arg2);
}

export function PickExistingVaultPath() {
  return window['go']['backend']['App']['PickExistingVaultPath']();
}

export function PickNewVaultPath() {
  return window['go']['backend']['App']['PickNewVaultPath']();
}

export function RenameVaultFile(arg1, arg2) {
  return window['go']['backend']['App']['RenameVaultFile'](arg1, arg2);
}

export function UnlockVaultAtPath(arg1, arg2) {
  return window['go']['backend']['App']['UnlockVaultAtPath'](arg1, arg2);
}

export function VaultUnlocked() {
  return window['go']['backend']['App']['VaultUnlocked']();
}
