// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddFileFromPathToVault(arg1:string,arg2:string):Promise<void>;

export function AddFileFromUrlToVault(arg1:string,arg2:string):Promise<void>;

export function AddFileToVault(arg1:string):Promise<void>;

export function CreateVaultFolder(arg1:string):Promise<void>;

export function DecryptURLForVaultPath(arg1:string):Promise<string>;

export function DeleteVaultPath(arg1:string):Promise<void>;

export function FinalizeNewVault(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDecryptedFileBase64(arg1:string):Promise<backend.DecryptedFile>;

export function GetSystemTheme():Promise<string>;

export function ListVaultFiles():Promise<Array<backend.VaultFileEntry>>;

export function LockVault():Promise<void>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function MoveVaultEntry(arg1:string,arg2:string):Promise<void>;

export function PickExistingVaultPath():Promise<string>;

export function PickNewVaultPath():Promise<string>;

export function RenameVaultFile(arg1:string,arg2:string):Promise<void>;

export function UnlockVaultAtPath(arg1:string,arg2:string):Promise<void>;

export function VaultUnlocked():Promise<boolean>;
